In [6]:
import numpy as np
import pandas as pd

In [17]:
subs = pd.read_csv(r"C:\Users\eryad\Downloads\subs.csv")
print(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [9]:
runs = pd.read_csv(r"C:\Users\eryad\Downloads\kohli_ipl.csv")
print(runs)

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [10]:
# astype
import sys
sys.getsizeof(runs)

3584

In [12]:
sys.getsizeof(runs.astype('int16'))

1004

In [18]:
# clip
subs.clip(100,200)

     Subscribers gained
0                   100
1                   100
2                   100
3                   100
4                   100
..                  ...
360                 200
361                 200
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [19]:
# drop duplicates
temp = pd.Series([1,1,2,2,3,3,4,4])
temp

0    1
1    1
2    2
3    2
4    3
5    3
6    4
7    4
dtype: int64

In [21]:
temp.drop_duplicates(keep='last')

1    1
3    2
5    3
7    4
dtype: int64

In [23]:
temp.duplicated().sum()

np.int64(4)

In [24]:
# isnull
temp = pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
temp

0     1.0
1     2.0
2     3.0
3     NaN
4     5.0
5     6.0
6     NaN
7     8.0
8     NaN
9    10.0
dtype: float64

In [25]:
temp.size

10

In [26]:
temp.count()

np.int64(7)

In [29]:
# isnull
temp.isnull().sum()

np.int64(3)

In [30]:
# dropna
temp.dropna()

0     1.0
1     2.0
2     3.0
4     5.0
5     6.0
7     8.0
9    10.0
dtype: float64

In [31]:
# fillna
temp.fillna(0)

0     1.0
1     2.0
2     3.0
3     0.0
4     5.0
5     6.0
6     0.0
7     8.0
8     0.0
9    10.0
dtype: float64

In [34]:
# isin
runs[(runs == 49) | (runs == 99)]

     match_no  runs
0         NaN   NaN
1         NaN   NaN
2         NaN   NaN
3         NaN   NaN
4         NaN   NaN
..        ...   ...
210       NaN   NaN
211       NaN   NaN
212       NaN   NaN
213       NaN   NaN
214       NaN   NaN

[215 rows x 2 columns]

In [35]:
runs[runs.isin([49,99])]

     match_no  runs
0         NaN   NaN
1         NaN   NaN
2         NaN   NaN
3         NaN   NaN
4         NaN   NaN
..        ...   ...
210       NaN   NaN
211       NaN   NaN
212       NaN   NaN
213       NaN   NaN
214       NaN   NaN

[215 rows x 2 columns]

In [ ]:
# copy
new = runs.head()

   match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1

In [43]:
new[1] = 1

C:\Users\eryad\AppData\Local\Temp\ipykernel_5740\2959015120.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new[1] = 1

In [44]:
new

   match_no  runs  1
0         1     1  1
1         2    23  1
2         3    13  1
3         4    12  1
4         5     1  1

In [ ]:
new = runs.head().copy

<bound method NDFrame.copy of    match_no  runs
0         1     1
1         2    23
2         3    13
3         4    12
4         5     1>

In [46]:
new[1] = 100

C:\Users\eryad\AppData\Local\Temp\ipykernel_5740\2515990219.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new[1] = 100

In [47]:
new

   match_no  runs    1
0         1     1  100
1         2    23  100
2         3    13  100
3         4    12  100
4         5     1  100

In [48]:
runs

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]