In [1]:
import numpy as np
import pandas as pd

In [2]:
# multiple index
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8],index= index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [3]:
# multiindex object creation
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex.levels[0]

# 2. pd.MultiIndex.from_product()
pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [4]:
# creating a series with multiindex object
s = pd.Series([1,2,3,4,5,6,7,8],index= multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [5]:
# fetch items from a series
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [6]:
# unstack
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [7]:
# stack
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [8]:
# multiindex dataframe
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index= multiindex,
    columns= ['avg_package','students']
)
branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [9]:
branch_df1.loc['cse']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [10]:
# multiindex df from columns 
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index=[2019,2020,2021,2022],
    columns=pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [11]:
branch_df2['delhi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [12]:
# multiindex df in terms of both cols and index
branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index= multiindex,
    columns= pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [13]:
# stacking and unstacking
branch_df1.unstack().unstack()

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [14]:
branch_df1.unstack().stack().stack()

C:\Users\eryad\AppData\Local\Temp\ipykernel_28656\2994828746.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack().stack()

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [15]:
branch_df2.stack()

C:\Users\eryad\AppData\Local\Temp\ipykernel_28656\3132666484.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df2.stack()

                  delhi  mumbai
2019 avg_package      1       0
     students         2       0
2020 avg_package      3       0
     students         4       0
2021 avg_package      5       0
     students         6       0
2022 avg_package      7       0
     students         8       0

In [16]:
# head and tail
branch_df3.head()
# shape
branch_df3.shape
# info
branch_df3.info()
# duplicated -> isnull
branch_df3.duplicated()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 632.0+ bytes

cse  2019    False
     2020    False
     2021    False
     2022    False
ece  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [17]:
branch_df3.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [18]:
branch_df3.stack()

C:\Users\eryad\AppData\Local\Temp\ipykernel_28656\4148153360.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df3.stack()

                      delhi  mumbai
cse 2019 avg_package      1       0
         students         2       0
    2020 avg_package      3       0
         students         4       0
    2021 avg_package      5       0
         students         6       0
    2022 avg_package      7       0
         students         8       0
ece 2019 avg_package      9       0
         students        10       0
    2020 avg_package     11       0
         students        12       0
    2021 avg_package     13       0
         students        14       0
    2022 avg_package     15       0
         students        16       0

In [19]:
# Extracting rows single
branch_df3.loc[('cse',2022)]

delhi   avg_package    7
        students       8
mumbai  avg_package    0
        students       0
Name: (cse, 2022), dtype: int64

In [20]:
# multiple rows
branch_df3.loc[('cse',2019):('ece',2020):2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [21]:
# using iloc
branch_df3.iloc[0:5:2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [22]:
# Extracting cols
branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [23]:
# multiple cols
branch_df3.iloc[:,1:3]

            delhi      mumbai
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

In [24]:
# Extracting both
branch_df3.iloc[[0,4],[1,2]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
ece 2019       10           0

In [25]:
# sort index
branch_df3.sort_index(ascending=False)
branch_df3.sort_index(ascending=[False,True])
# based on level
branch_df3.sort_index(level=1,ascending=[False])

               delhi               mumbai
         avg_package students avg_package students
cse 2022           7        8           0        0
ece 2022          15       16           0        0
cse 2021           5        6           0        0
ece 2021          13       14           0        0
cse 2020           3        4           0        0
ece 2020          11       12           0        0
cse 2019           1        2           0        0
ece 2019           9       10           0        0

In [26]:
# multiindex dataframe(col) -> Transpose
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

In [27]:
# swap level
branch_df3.swaplevel(axis=1)

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [28]:
# Long vs wide Data
# melt -> wide to long
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [29]:
pd.DataFrame({'cse':[129],'ece':[102],'mech':[52]}).melt(var_name='branch',value_name='students')

  branch  students
0    cse       129
1    ece       102
2   mech        52

In [30]:
pd.DataFrame({
    'branch':['cse','ece','mech'],
    '2020':[100,200,90],
    '2021':[129,90,99],
    '2022':[200,87,87]
}).melt(id_vars=['branch'],var_name='year',value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       200
2   mech  2020        90
3    cse  2021       129
4    ece  2021        90
5   mech  2021        99
6    cse  2022       200
7    ece  2022        87
8   mech  2022        87

In [31]:
# melt -> real world example
death = pd.read_csv(r"C:\Users\eryad\Downloads\time_series_covid19_confirmed_global.csv")
confirm = pd.read_csv(r"C:\Users\eryad\Downloads\time_series_covid19_confirmed_global.csv")
confirm.head(2)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812

In [32]:
death = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')
confirm = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')

In [33]:
death.head()

  Province/State Country/Region       Lat       Long     date  num_deaths
0            NaN    Afghanistan  33.93911  67.709953  1/22/20           0
1            NaN        Albania  41.15330  20.168300  1/22/20           0
2            NaN        Algeria  28.03390   1.659600  1/22/20           0
3            NaN        Andorra  42.50630   1.521800  1/22/20           0
4            NaN         Angola -11.20270  17.873900  1/22/20           0

In [36]:
confirm.head(1)

  Province/State Country/Region       Lat       Long     date  num_cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20          0

In [37]:
confirm.merge(death,on=['Province/State','Country/Region','Lat','Long'])[['Country/Region','date','num_cases','num_deaths']]

KeyboardInterrupt: